[package]
name = "push_macros"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
readme = "README.md"
repository = { workspace = true }
license = { workspace = true }
keywords = ["builder-pattern", "proc-macros", "push"]
categories = ["development-tools"]
publish = { workspace = true }

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ident_case_conversions = "1.0.0"
itertools = { workspace = true }
macro_railroad_annotation = { workspace = true }
manyhow = "0.11.4"
prettyplease = "0.2.15"
proc-macro-assertions = "0.1.5"
proc-macro2 = "1.0.81"
quote = "1.0.33"
syn = { version = "2.0.58", features = ["full", "printing"] }
