[package]
name = "push_macros"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[lib]
proc-macro=true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ident_case_conversions = "1.0.0"
manyhow = "0.8.1"
proc-macro-assertions = "0.1.5"
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = { version = "2.0.38", features = ["full", "printing"] }
itertools = { workspace = true }
prettyplease = "0.2.15"
macro_railroad_annotation = { workspace = true }
