allowed-duplicate-crates = [
  "base64",
  "itertools",
  # https://github.com/sunfishcode/is-terminal/pull/45/files
  "windows-targets",
  "windows-sys",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
  # miette dependency, already updated on main but not released yet.
  "unicode-width"
]
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
doc-valid-idents = ["McPhee", ".."]
