[package]
name = "ec_macros"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
readme = "README.md"
repository = { workspace = true }
license = { workspace = true }
keywords = [
  "evolutionary-computation-macros",
  "framework",
  "genetic",
  "genetic-algorithm",
]
categories = ["development-tools"]
publish = { workspace = true }

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manyhow = "0.11.4"
proc-macro2 = "1.0.81"
quote = "1.0.33"
syn = { version = "2.0.58", features = ["full", "printing"] }
